# Site settings
title: Bring Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://developer.bring.com" # the base hostname & protocol for your site
permalink: /blog/:title/

# RAML settings
raml_map:
  api/shipping-guide/api.raml: api/shipping-guide/index.html
  api/pickup-point/api.raml: api/pickup-point/index.html
  api/booking/api.raml: api/booking/index.html
  api/tracking/api.raml: api/tracking/index.html
  api/reports/api.raml: api/reports/index.html
  api/invoice/api.raml: api/invoice/index.html
  api/postal-code/api.raml: api/postal-code/index.html
  api/easy-return-service/api.raml: api/easy-return-service/index.html
  api/order-management/api.raml: api/order-management/index.html

# Build settings
gems:
- jekyll-paginate
- jekyll-archives

paginate: 10
paginate_path: /blog/page/:num # default is page:num

jekyll-archives:
  enabled: [categories]
  layouts:
    category: archives/category
  permalinks:
    category: '/blog/category/:name/'

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed

exclude: [Rakefile, Gemfile, Gemfile.lock, README.md, bower.json, developer-site.iml, node_modules, LICENSE]
